In [3]:
import pandas as pd
import numpy as np

In [4]:
customer_churn_df = pd.read_csv(r"C:\Users\Arpita\Desktop\Customer Churn Prediction\data\processed\churned_or_stayed_df.csv", keep_default_na = False)
pd.set_option('display.max_columns', None)

In [5]:
customer_churn_df

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,Tenure in Months,Offer,Phone Service,Avg Monthly Long Distance Charges,Multiple Lines,Internet Service,Internet Type,Avg Monthly GB Download,Online Security,Online Backup,Device Protection Plan,Premium Tech Support,Streaming TV,Streaming Movies,Streaming Music,Unlimited Data,Contract,Paperless Billing,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason,Age Groups,Churned,Churned Senior,Tenure Groups in Months,Churned Early Tenure,Monthly Charge Quartile,Online Security Int,Online Backup Int,Device Protection Plan Int,Premium Tech Support Int,Streaming TV Int,Streaming Movies Int,Streaming Music Int,Protective Services Count,Streaming Services Count,Referral Group
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,9,None,Yes,42.39,No,Yes,Cable,16.0,No,Yes,No,Yes,Yes,No,No,Yes,One Year,Yes,Credit Card,65.60,593.30,0.0,0,381.51,974.81,Stayed,,,35-44,0,0,7-12,0,Q2\n ($40.60-72.90),0,1,0,1,1,0,0,2,1,2-3
1,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,4,Offer E,Yes,33.65,No,Yes,Fiber Optic,30.0,No,No,Yes,No,No,No,No,Yes,Month-to-Month,Yes,Bank Withdrawal,73.90,280.85,0.0,0,134.60,415.45,Churned,Competitor,Competitor had better devices,45-54,1,0,0-6,1,Q3\n ($72.95-90.60),0,0,1,0,0,0,0,1,0,0
2,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,13,Offer D,Yes,27.82,No,Yes,Fiber Optic,4.0,No,Yes,Yes,No,Yes,Yes,No,Yes,Month-to-Month,Yes,Bank Withdrawal,98.00,1237.85,0.0,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction,75-80,1,1,13-24,0,Q4\n ($90.65-118.75),0,1,1,0,1,1,0,2,2,1
3,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,3,None,Yes,7.38,No,Yes,Fiber Optic,11.0,No,No,No,Yes,Yes,No,No,Yes,Month-to-Month,Yes,Credit Card,83.90,267.40,0.0,0,22.14,289.54,Churned,Dissatisfaction,Network reliability,75-80,1,1,0-6,1,Q3\n ($72.95-90.60),0,0,0,1,1,0,0,1,1,2-3
4,0013-MHZWF,Female,23,No,3,Midpines,95345,37.581496,-119.972762,0,9,Offer E,Yes,16.77,No,Yes,Cable,73.0,No,No,No,Yes,Yes,Yes,Yes,Yes,Month-to-Month,Yes,Credit Card,69.40,571.45,0.0,0,150.93,722.38,Stayed,,,18-24,0,0,7-12,0,Q2\n ($40.60-72.90),0,0,0,1,1,1,1,1,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6470,9986-BONCE,Female,36,No,0,Fallbrook,92028,33.362575,-117.299644,0,4,None,Yes,2.01,No,No,None,0.0,No,No,No,No,No,No,No,No,Month-to-Month,No,Bank Withdrawal,20.95,85.50,0.0,0,8.04,93.54,Churned,Competitor,Competitor made better offer,35-44,1,0,0-6,1,Q1\n ($18.25-40.55),0,0,0,0,0,0,0,0,0,0
6471,9987-LUTYD,Female,20,No,0,La Mesa,91941,32.759327,-116.997260,0,13,Offer D,Yes,46.68,No,Yes,DSL,59.0,Yes,No,No,Yes,No,No,Yes,Yes,One Year,No,Credit Card,55.15,742.90,0.0,0,606.84,1349.74,Stayed,,,18-24,0,0,13-24,0,Q2\n ($40.60-72.90),1,0,0,1,0,0,1,2,1,0
6472,9992-RRAMN,Male,40,Yes,0,Riverbank,95367,37.734971,-120.954271,1,22,Offer D,Yes,16.20,Yes,Yes,Fiber Optic,17.0,No,No,No,No,No,Yes,Yes,Yes,Month-to-Month,Yes,Bank Withdrawal,85.10,1873.70,0.0,0,356.40,2230.10,Churned,Dissatisfaction,Product dissatisfaction,35-44,1,0,13-24,0,Q3\n ($72.95-90.60),0,0,0,0,0,1,1,0,2,1
6473,9993-LHIEB,Male,21,Yes,0,Solana Beach,92075,33.001813,-117.263628,5,67,Offer A,Yes,2.12,No,Yes,Cable,58.0,Yes,No,Yes,Yes,No,Yes,Yes,Yes,Two Year,No,Credit Card,67.85,4627.65,0.0,0,142.04,4769.69,Stayed,,,18-24,0,0,49-72,0,Q2\n ($40.60-72.90),1,0,1,1,0,1,1,3,2,4-5


In [6]:
high_churn_cities = ['San Diego', 'Fallbrook', 'Temecula', 'Glendale', 'Escondido', 'San Francisco', 'Berkeley', 'Stockton', 'Los Angeles', 'Oakland', 'San Jose', 'Sacramento', 'Long Beach']
customer_churn_df['High Churn City'] = (customer_churn_df['City'].isin(high_churn_cities)).astype(int)

In [7]:
customer_churn_df = customer_churn_df.drop(columns=['Customer ID', 'City', 'Zip Code', 'Latitude', 'Longitude', 'Avg Monthly GB Download', 'Total Charges', 'Customer Status', 'Churn Category', 'Churn Reason', 'Age Groups',
                                'Churned Senior', 'Tenure Groups in Months', 'Churned Early Tenure', 'Monthly Charge Quartile', 'Online Security', 'Online Backup',	'Device Protection Plan',	
                                'Premium Tech Support', 'Streaming TV',	'Streaming Movies',	'Streaming Music', 'Protective Services Count',	'Streaming Services Count',	'Referral Group', 'Total Revenue', 'Total Extra Data Charges', 
                                'Total Long Distance Charges', 'Total Refunds'])

In [8]:
customer_churn_df

,Gender,Age,Married,Number of Dependents,Number of Referrals,Tenure in Months,Offer,Phone Service,Avg Monthly Long Distance Charges,Multiple Lines,Internet Service,Internet Type,Unlimited Data,Contract,Paperless Billing,Payment Method,Monthly Charge,Churned,Online Security Int,Online Backup Int,Device Protection Plan Int,Premium Tech Support Int,Streaming TV Int,Streaming Movies Int,Streaming Music Int,High Churn City
0,Female,37,Yes,0,2,9,None,Yes,42.39,No,Yes,Cable,Yes,One Year,Yes,Credit Card,65.60,0,0,1,0,1,1,0,0,0
1,Male,50,No,0,0,4,Offer E,Yes,33.65,No,Yes,Fiber Optic,Yes,Month-to-Month,Yes,Bank Withdrawal,73.90,1,0,0,1,0,0,0,0,0
2,Male,78,Yes,0,1,13,Offer D,Yes,27.82,No,Yes,Fiber Optic,Yes,Month-to-Month,Yes,Bank Withdrawal,98.00,1,0,1,1,0,1,1,0,0
3,Female,75,Yes,0,3,3,None,Yes,7.38,No,Yes,Fiber Optic,Yes,Month-to-Month,Yes,Credit Card,83.90,1,0,0,0,1,1,0,0,0
4,Female,23,No,3,0,9,Offer E,Yes,16.77,No,Yes,Cable,Yes,Month-to-Month,Yes,Credit Card,69.40,0,0,0,0,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6470,Female,36,No,0,0,4,None,Yes,2.01,No,No,None,No,Month-to-Month,No,Bank Withdrawal,20.95,1,0,0,0,0,0,0,0,1
6471,Female,20,No,0,0,13,Offer D,Yes,46.68,No,Yes,DSL,Yes,One Year,No,Credit Card,55.15,0,1,0,0,1,0,0,1,0
6472,Male,40,Yes,0,1,22,Offer D,Yes,16.20,Yes,Yes,Fiber Optic,Yes,Month-to-Month,Yes,Bank Withdrawal,85.10,1,0,0,0,0,0,1,1,0
6473,Male,21,Yes,0,5,67,Offer A,Yes,2.12,No,Yes,Cable,Yes,Two Year,No,Credit Card,67.85,0,1,0,1,1,0,1,1,0


In [9]:
customer_churn_df.columns

Index(['Gender', 'Age', 'Married', 'Number of Dependents',
       'Number of Referrals', 'Tenure in Months', 'Offer', 'Phone Service',
       'Avg Monthly Long Distance Charges', 'Multiple Lines',
       'Internet Service', 'Internet Type', 'Unlimited Data', 'Contract',
       'Paperless Billing', 'Payment Method', 'Monthly Charge', 'Churned',
       'Online Security Int', 'Online Backup Int',
       'Device Protection Plan Int', 'Premium Tech Support Int',
       'Streaming TV Int', 'Streaming Movies Int', 'Streaming Music Int',
       'High Churn City'],
      dtype='str')

In [10]:
customer_churn_df['Payment Method'].value_counts()

Payment Method
Bank Withdrawal    3669
Credit Card        2469
Mailed Check        337
Name: count, dtype: int64

In [11]:
customer_churn_df['Gender'] = customer_churn_df['Gender'].map({'Male': 1, 'Female': 0})
binary_cols = ['Married', 'Phone Service', 'Multiple Lines', 'Internet Service', 'Unlimited Data', 'Paperless Billing']
for col in binary_cols:
    customer_churn_df[col] = customer_churn_df[col].map({'Yes': 1, 'No': 0})

# customer_churn_df['Married'] = customer_churn_df['Married'].map({'Yes': 1, 'No': 0})
# customer_churn_df['Phone Service'] = customer_churn_df['Phone Service'].map({'Yes': 1, 'No': 0})
# customer_churn_df['Multiple Lines'] = customer_churn_df['Multiple Lines'].map({'Yes': 1, 'No': 0})
# customer_churn_df['Internet Service'] = customer_churn_df['Internet Service'].map({'Yes': 1, 'No': 0})
# customer_churn_df['Unlimited Data'] = customer_churn_df['Unlimited Data'].map({'Yes': 1, 'No': 0})
# customer_churn_df['Paperless Billing'] = customer_churn_df['Paperless Billing'].map({'Yes': 1, 'No': 0})

In [12]:
customer_churn_df[['Married', 'Phone Service', 'Multiple Lines', 'Internet Service', 'Unlimited Data', 'Paperless Billing', 'Gender']].isnull().sum()

Married              0
Phone Service        0
Multiple Lines       0
Internet Service     0
Unlimited Data       0
Paperless Billing    0
Gender               0
dtype: int64

In [13]:
customer_churn_df

,Gender,Age,Married,Number of Dependents,Number of Referrals,Tenure in Months,Offer,Phone Service,Avg Monthly Long Distance Charges,Multiple Lines,Internet Service,Internet Type,Unlimited Data,Contract,Paperless Billing,Payment Method,Monthly Charge,Churned,Online Security Int,Online Backup Int,Device Protection Plan Int,Premium Tech Support Int,Streaming TV Int,Streaming Movies Int,Streaming Music Int,High Churn City
0,0,37,1,0,2,9,None,1,42.39,0,1,Cable,1,One Year,1,Credit Card,65.60,0,0,1,0,1,1,0,0,0
1,1,50,0,0,0,4,Offer E,1,33.65,0,1,Fiber Optic,1,Month-to-Month,1,Bank Withdrawal,73.90,1,0,0,1,0,0,0,0,0
2,1,78,1,0,1,13,Offer D,1,27.82,0,1,Fiber Optic,1,Month-to-Month,1,Bank Withdrawal,98.00,1,0,1,1,0,1,1,0,0
3,0,75,1,0,3,3,None,1,7.38,0,1,Fiber Optic,1,Month-to-Month,1,Credit Card,83.90,1,0,0,0,1,1,0,0,0
4,0,23,0,3,0,9,Offer E,1,16.77,0,1,Cable,1,Month-to-Month,1,Credit Card,69.40,0,0,0,0,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6470,0,36,0,0,0,4,None,1,2.01,0,0,None,0,Month-to-Month,0,Bank Withdrawal,20.95,1,0,0,0,0,0,0,0,1
6471,0,20,0,0,0,13,Offer D,1,46.68,0,1,DSL,1,One Year,0,Credit Card,55.15,0,1,0,0,1,0,0,1,0
6472,1,40,1,0,1,22,Offer D,1,16.20,1,1,Fiber Optic,1,Month-to-Month,1,Bank Withdrawal,85.10,1,0,0,0,0,0,1,1,0
6473,1,21,1,0,5,67,Offer A,1,2.12,0,1,Cable,1,Two Year,0,Credit Card,67.85,0,1,0,1,1,0,1,1,0


In [14]:
customer_churn_df = pd.get_dummies(customer_churn_df, columns=['Offer', 'Internet Type', 'Contract', 'Payment Method'], drop_first=False, dtype = int)
customer_churn_df = customer_churn_df.drop(columns= ['Offer_None', 'Internet Type_None', 'Contract_Month-to-Month', 'Payment Method_Bank Withdrawal'])

In [15]:
customer_churn_df

,Gender,Age,Married,Number of Dependents,Number of Referrals,Tenure in Months,Phone Service,Avg Monthly Long Distance Charges,Multiple Lines,Internet Service,Unlimited Data,Paperless Billing,Monthly Charge,Churned,Online Security Int,Online Backup Int,Device Protection Plan Int,Premium Tech Support Int,Streaming TV Int,Streaming Movies Int,Streaming Music Int,High Churn City,Offer_Offer A,Offer_Offer B,Offer_Offer C,Offer_Offer D,Offer_Offer E,Internet Type_Cable,Internet Type_DSL,Internet Type_Fiber Optic,Contract_One Year,Contract_Two Year,Payment Method_Credit Card,Payment Method_Mailed Check
0,0,37,1,0,2,9,1,42.39,0,1,1,1,65.60,0,0,1,0,1,1,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0
1,1,50,0,0,0,4,1,33.65,0,1,1,1,73.90,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
2,1,78,1,0,1,13,1,27.82,0,1,1,1,98.00,1,0,1,1,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0
3,0,75,1,0,3,3,1,7.38,0,1,1,1,83.90,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0
4,0,23,0,3,0,9,1,16.77,0,1,1,1,69.40,0,0,0,0,1,1,1,1,0,0,0,0,0,1,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6470,0,36,0,0,0,4,1,2.01,0,0,0,0,20.95,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
6471,0,20,0,0,0,13,1,46.68,0,1,1,0,55.15,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,1,0,1,0
6472,1,40,1,0,1,22,1,16.20,1,1,1,1,85.10,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,1,0,0,0,0
6473,1,21,1,0,5,67,1,2.12,0,1,1,0,67.85,0,1,0,1,1,0,1,1,0,1,0,0,0,0,1,0,0,0,1,1,0


In [16]:
customer_churn_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6475 entries, 0 to 6474
Data columns (total 34 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   Gender                             6475 non-null   int64  
 1   Age                                6475 non-null   int64  
 2   Married                            6475 non-null   int64  
 3   Number of Dependents               6475 non-null   int64  
 4   Number of Referrals                6475 non-null   int64  
 5   Tenure in Months                   6475 non-null   int64  
 6   Phone Service                      6475 non-null   int64  
 7   Avg Monthly Long Distance Charges  6475 non-null   float64
 8   Multiple Lines                     6475 non-null   int64  
 9   Internet Service                   6475 non-null   int64  
 10  Unlimited Data                     6475 non-null   int64  
 11  Paperless Billing                  6475 non-null   int64  
 12  Mon

In [17]:
X = customer_churn_df.drop(columns= ['Churned'])
y = customer_churn_df['Churned']

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [20]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(5180, 33)
(1295, 33)
(5180,)
(1295,)


In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
lr_model = LogisticRegression()
main_scaler = StandardScaler()
X_train_scaled = main_scaler.fit_transform(X_train)
X_test_scaled = main_scaler.transform(X_test)
lr_model.fit(X_train_scaled, y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default sol

In [22]:
pd.DataFrame(X_train_scaled).mean().round(2)

0    -0.0
1    -0.0
2    -0.0
3     0.0
4    -0.0
5    -0.0
6     0.0
7    -0.0
8     0.0
9     0.0
10    0.0
11   -0.0
12    0.0
13    0.0
14   -0.0
15    0.0
16    0.0
17   -0.0
18    0.0
19   -0.0
20   -0.0
21   -0.0
22   -0.0
23   -0.0
24   -0.0
25   -0.0
26   -0.0
27    0.0
28   -0.0
29   -0.0
30   -0.0
31   -0.0
32   -0.0
dtype: float64

In [23]:
y_pred= lr_model.predict(X_test_scaled)
print(y_pred[:10])

[0 1 0 0 0 1 0 0 1 1]


In [24]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.91      0.90       927
           1       0.76      0.74      0.75       368

    accuracy                           0.86      1295
   macro avg       0.83      0.82      0.83      1295
weighted avg       0.86      0.86      0.86      1295



In [25]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[840  87]
 [ 96 272]]


- A Logistic Regression model was trained to predict customer churn because the target variable (Churned) is binary (0 = Not Churned, 1 = Churned). Logistic Regression provides a strong, interpretable baseline classifier that estimates the probability of churn while allowing straightforward analysis of model performance.

- Model Performance:
Accuracy: 86%
Precision (Class 1 – Churned): 76%
Recall (Class 1 – Churned): 74%
F1-Score (Class 1 – Churned): 75%
- Although the model achieves 86% accuracy, this should be interpreted in context. Since 71.6% of customers did not churn, a naïve model predicting every customer as "Not Churned" would already achieve 71.6% accuracy. Therefore, the improvement to 86%, combined with a 74% recall for churners, demonstrates that the model is learning meaningful churn patterns rather than relying on the majority class.

- Business Interpretation: 
The confusion matrix contains 96 False Negatives, meaning 96 customers who actually churned were incorrectly predicted as non-churners. Based on the dataset's median monthly charge of $79.65, these missed churners represent approximately $91,000+ in annual recurring revenue at risk. These customers would likely receive no retention intervention and therefore be lost to the business.
The model also produced 87 False Positives, meaning 87 customers would unnecessarily receive retention offers. Assuming a retention call or incentive costs approximately $20–$50 per customer, the unnecessary intervention cost is only around $2,000–$4,000.

This creates an approximate 20:1 cost ratio in favour of reducing False Negatives. A missed churner costs roughly $950 per year, whereas an unnecessary retention action costs around $50.

- Recommendation:
The current model uses the default 0.5 probability threshold, which provides a balanced trade-off between precision and recall. However, given that the business cost of a missed churner is approximately 20 times greater than the cost of an unnecessary retention call, the decision threshold should be reduced to 0.3.
Lowering the threshold to 0.3 is expected to increase recall by identifying more at-risk customers, even if it results in additional False Positives. From a business perspective, spending slightly more on retention campaigns is a worthwhile trade-off to prevent approximately $91,000+ in annual revenue loss from missed churners.

In [26]:
y_proba = lr_model.predict_proba(X_test_scaled)
y_pred_03 = (y_proba[:,1] >= 0.3).astype(int)
print(classification_report(y_test, y_pred_03))
print(confusion_matrix(y_test, y_pred_03))

              precision    recall  f1-score   support

           0       0.94      0.83      0.88       927
           1       0.67      0.87      0.75       368

    accuracy                           0.84      1295
   macro avg       0.80      0.85      0.82      1295
weighted avg       0.86      0.84      0.84      1295

[[768 159]
 [ 49 319]]


In [27]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators= 100, random_state=42)
rf_model.fit(X_train_scaled, y_train)
y_pred = rf_model.predict(X_test_scaled)

from sklearn.metrics import(classification_report, confusion_matrix)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.95      0.92       927
           1       0.84      0.69      0.76       368

    accuracy                           0.88      1295
   macro avg       0.86      0.82      0.84      1295
weighted avg       0.87      0.88      0.87      1295

[[879  48]
 [113 255]]


In [28]:
y_prob = rf_model.predict_proba(X_test_scaled)[:,1]
y_pred_03 = np.where(y_prob >= 0.3, 1,0)
print(classification_report(y_test, y_pred_03))
print(confusion_matrix(y_test, y_pred_03))

              precision    recall  f1-score   support

           0       0.94      0.85      0.89       927
           1       0.70      0.87      0.77       368

    accuracy                           0.86      1295
   macro avg       0.82      0.86      0.83      1295
weighted avg       0.87      0.86      0.86      1295

[[789 138]
 [ 48 320]]


Four model configurations were evaluated to determine the most cost-effective approach for customer churn prediction. Performance was assessed using classification metrics as well as a business cost function where each False Negative (missed churner) costs $950 and each False Positive (unnecessary retention action) costs $50.
- Logistic Regression (Threshold = 0.5): 
Recall(Churn) = 0.74, Precision (Churn) = 0.75, False Positives = 87, False Negatives = 96, Total Business Cost = $95,550
- Logistic Regression (Threshold = 0.3): 
Recall(Churn) = 0.87, Precision (Churn) = 0.67, False Positives = 159, False Negatives = 49, Total Business Cost = $54,500
- Random Forest (Threshold = 0.5): 
Recall(Churn) = 0.69, Precision (Churn) = 0.84, False Positives = 48, False Negatives = 113, Total Business Cost = $109,750
- Random Forest (Threshold = 0.3): 
Recall(Churn) = 0.87, Precision (Churn) = 0.70, False Positives = 138, False Negatives = 48, Total Business Cost = $52,500

- Interpretation:
At the default threshold (0.5), Logistic Regression outperformed Random Forest from a business perspective despite having lower overall accuracy. Random Forest was more conservative, resulting in fewer false positives but substantially more false negatives. Since the cost of missing a churning customer ($950) was far greater than the cost of an unnecessary retention action ($50), the additional false negatives made Random Forest the more expensive model.
Lowering the decision threshold from 0.5 to 0.3 significantly improved the recall of both models by identifying more churning customers. Both Logistic Regression and Random Forest achieved a recall of 0.87, reducing false negatives from 96/113 to 48. Although this increased the number of false positives, the reduction in missed churners produced a substantial decrease in overall business cost.
Among the four scenarios, Random Forest with a threshold of 0.3 delivered the best overall performance. It achieved the same churn recall as Logistic Regression while producing fewer false positives (138 vs. 159), resulting in the lowest total business cost of $52,500. This represents an estimated saving of approximately $2,000 over Logistic Regression at the same threshold.

- Recommended Model: Based on the defined business objective of minimizing financial loss due to customer churn, Random Forest with a decision threshold of 0.3 is the recommended model. It balances high churn detection with fewer unnecessary retention interventions, producing the lowest estimated business cost among all evaluated models.

- Limitation: The observed improvement over Logistic Regression is relatively small (approximately $2,000 on the test set, equivalent to roughly $10,000 when scaled to the full dataset). Since these results are based on a single train-test split, they may vary with different samples. Before deployment, the model should be validated using techniques such as cross-validation or repeated train-test splits to confirm that the improvement is consistent and statistically reliable.


In [29]:
feature_importance = pd.Series(
    rf_model.feature_importances_ , index = X.columns
).sort_values(ascending = False)
feature_importance

Tenure in Months                     0.225069
Monthly Charge                       0.095918
Number of Referrals                  0.077846
Age                                  0.077767
Avg Monthly Long Distance Charges    0.068326
Contract_Two Year                    0.066721
Contract_One Year                    0.037547
Number of Dependents                 0.032125
Internet Type_Fiber Optic            0.031030
Offer_Offer E                        0.024418
Online Security Int                  0.020262
Payment Method_Credit Card           0.019705
Premium Tech Support Int             0.018373
Paperless Billing                    0.016761
Married                              0.015366
High Churn City                      0.015034
Gender                               0.014647
Online Backup Int                    0.013764
Multiple Lines                       0.012323
Device Protection Plan Int           0.012237
Streaming TV Int                     0.012097
Unlimited Data                    

- The Random Forest model identified the following as the five most important predictors of customer churn:
Tenure in Months (0.2251), Monthly Charge (0.0959), Number of Referrals (0.0778), Age (0.0778) and Avg Monthly Long Distance Charges (0.0683)

- Comparison with EDA:
The feature importance results are largely consistent with the findings from the Exploratory Data Analysis (EDA). Tenure in Months emerged as the most influential feature by a considerable margin, confirming the earlier observation that customers with shorter tenure are significantly more likely to churn.
Monthly Charge also ranked as one of the strongest predictors, but this should not be interpreted as "higher monthly charges always lead to higher churn." During EDA, churn increased from the lowest charge group to the middle-high charge group (Q3) and then declined slightly in the highest charge group (Q4). This indicates a non-monotonic relationship rather than a simple increasing trend. Despite this, Monthly Charge remains highly valuable because the Random Forest can create decision splits around meaningful charge thresholds that effectively separate customers with different churn risks.
The importance of Number of Referrals was higher than expected. Customers who refer others are likely to be more satisfied and engaged with the company's services, making them less likely to churn. Tree-based models can effectively distinguish between customers with few or no referrals and those with multiple referrals, allowing this feature to contribute strongly to prediction.
Similarly, Age emerged as an important predictor. Rather than assuming a linear relationship, the Random Forest can identify specific age ranges where churn behavior differs. This ability to model complex, non-linear patterns explains why Age contributes more to prediction than was immediately apparent from univariate EDA.

- One-Hot Encoding Dilution Effect:
Categorical variables such as Contract and value-added services (Online Security, Premium Tech Support, Device Protection, Online Backup, etc.) were converted into multiple binary (dummy) variables using one-hot encoding. As a result, the importance of the original categorical variable is distributed across several columns. For example, Contract_Two Year and Contract_One Year appear separately in the ranking, but together they demonstrate that contract type is one of the strongest drivers of churn. Likewise, although each protective service has only moderate individual importance, their combined contribution indicates that customers using these services are generally more loyal and less likely to churn.

- Business Interpretation:
From a business perspective, the model highlights several actionable factors that can be targeted to reduce churn. Customers with low tenure should receive proactive onboarding, engagement campaigns, and early retention offers during their first few months, as this is the period of highest churn risk. The importance of Monthly Charge suggests that pricing influences churn, but not in a simple linear way. Instead of reducing prices for all customers, the company should identify pricing segments with elevated churn risk and offer targeted discounts or bundled plans where appropriate. The strong influence of Contract indicates that encouraging customers to move from month-to-month plans to one- or two-year contracts can significantly improve retention. Finally, promoting value-added services such as Online Security, Premium Tech Support, and Device Protection can increase customer engagement and loyalty, further reducing the likelihood of churn. Together, these insights provide clear operational strategies that align with the model's most influential predictors and support more effective customer retention efforts.

Now cross validation

In [30]:
def business_cost (y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    total_cost = (fn * 950) + (fp * 50)
    return total_cost
from sklearn.metrics import make_scorer
cost_scorer = make_scorer(business_cost, greater_is_better= False)

In [31]:
from sklearn.model_selection import StratifiedKFold 
skf = StratifiedKFold(n_splits = 5, shuffle = True, random_state = 42)

In [32]:
rf_costs = []
for train_idx, test_idx in skf.split(X,y):
    X_train_fold = X.iloc[train_idx]
    X_test_fold = X.iloc[test_idx]
    y_train_fold = y.iloc[train_idx]
    y_test_fold = y.iloc[test_idx]
    fold_scaler = StandardScaler()
    X_train_scaled = fold_scaler.fit_transform(X_train_fold)
    X_test_scaled = fold_scaler.transform(X_test_fold)
    rf = RandomForestClassifier(n_estimators=500, random_state=42)
    rf.fit(X_train_scaled, y_train_fold)
    y_prob = rf.predict_proba(X_test_scaled)[:,1]
    y_pred = (y_prob >= 0.3).astype(int)
    cost = business_cost(y_test_fold, y_pred)
    rf_costs.append(cost)

print('Business cost for each fold: ', rf_costs)
print('Average Business Cost: ', np.mean(rf_costs))
print('Standard Deviation: ', np.std(rf_costs))

Business cost for each fold:  [np.int64(60050), np.int64(68450), np.int64(69000), np.int64(55500), np.int64(56550)]
Average Business Cost:  61910.0
Standard Deviation:  5767.4431076517785


In [33]:
lr_costs = []
for train_idx, test_idx in skf.split(X,y):
    X_train_fold = X.iloc[train_idx]
    X_test_fold = X.iloc[test_idx]
    y_train_fold = y.iloc[train_idx]
    y_test_fold = y.iloc[test_idx]
    fold_scaler = StandardScaler()
    X_train_scaled = fold_scaler.fit_transform(X_train_fold)
    X_test_scaled = fold_scaler.transform(X_test_fold)
    lr = LogisticRegression(random_state=42)
    lr.fit(X_train_scaled, y_train_fold)
    y_prob = lr.predict_proba(X_test_scaled)[:,1]
    y_pred = (y_prob >= 0.3).astype(int)
    cost = business_cost(y_test_fold, y_pred)
    lr_costs.append(cost)

print('Business cost for each fold: ', lr_costs)
print('Average Business Cost: ', np.mean(lr_costs))
print('Standard Deviation: ', np.std(lr_costs))

Business cost for each fold:  [np.int64(53900), np.int64(65700), np.int64(61000), np.int64(55750), np.int64(56350)]
Average Business Cost:  58540.0
Standard Deviation:  4276.143122020122


- Recommended Model (Updated After Cross-Validation):

The initial train-test split suggested that Random Forest (threshold = 0.3) was the better model, achieving a business cost of $52,500 compared to $54,500 for Logistic Regression. However, this conclusion was based on a single train-test split, which may not be representative of the model's true performance on unseen data.

To validate this result, I performed 5-fold Stratified Cross-Validation, ensuring that each fold preserved the original churn/non-churn class distribution. For each fold, the preprocessing pipeline was repeated correctly by fitting the scaler only on the training fold, training a fresh model, predicting probabilities, applying the deployment threshold of 0.3, and calculating the custom business cost.

The cross-validation results showed:
Logistic Regression @ 0.3: Mean Business Cost= $58,540 and Standard Deviation= $4,276
Random Forest @ 0.3: Mean Business Cost= $61,910 and Standard Deviation= $5,767

Logistic Regression achieved a lower average business cost and lower variability across the five folds. It also outperformed Random Forest in 4 of the 5 validation folds, indicating that its superior performance was more consistent across different data splits.

- Final Recommendation: Based on the cross-validated results, Logistic Regression with a decision threshold of 0.3 is recommended for deployment. Although Random Forest appeared superior on the initial train-test split, cross-validation demonstrated that this was not a reliable basis for model selection. Evaluating both models across multiple stratified folds provided a more robust estimate of real-world performance and showed that Logistic Regression is expected to produce the lower business cost while delivering more consistent results.



In [34]:
print(X.shape)

(6475, 33)


In [35]:
print(X.columns)

Index(['Gender', 'Age', 'Married', 'Number of Dependents',
       'Number of Referrals', 'Tenure in Months', 'Phone Service',
       'Avg Monthly Long Distance Charges', 'Multiple Lines',
       'Internet Service', 'Unlimited Data', 'Paperless Billing',
       'Monthly Charge', 'Online Security Int', 'Online Backup Int',
       'Device Protection Plan Int', 'Premium Tech Support Int',
       'Streaming TV Int', 'Streaming Movies Int', 'Streaming Music Int',
       'High Churn City', 'Offer_Offer A', 'Offer_Offer B', 'Offer_Offer C',
       'Offer_Offer D', 'Offer_Offer E', 'Internet Type_Cable',
       'Internet Type_DSL', 'Internet Type_Fiber Optic', 'Contract_One Year',
       'Contract_Two Year', 'Payment Method_Credit Card',
       'Payment Method_Mailed Check'],
      dtype='str')


In [ ]:
import pickle
import os

MODELS_DIR = os.path.join("..", "models")

with open(os.path.join(MODELS_DIR, "model.pkl"), "wb") as f:
    pickle.dump(lr_model, f)

with open(os.path.join(MODELS_DIR, "scaler.pkl"), "wb") as f:
    pickle.dump(main_scaler, f) 

feature_columns = X.columns.tolist()
with open(os.path.join(MODELS_DIR, "feature_columns.pkl"), "wb") as f:
    pickle.dump(feature_columns, f)

with open(os.path.join(MODELS_DIR, "high_churn_cities.pkl"), "wb") as f:
    pickle.dump(high_churn_cities, f)

print("All deployment artifacts saved successfully!")